name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
